// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8_uN5EMnGOvYjl7PgIfEsmAq5nwc-c8k',
    appId: '1:246167719483:web:691fd6340fedc3d257161e',
    messagingSenderId: '246167719483',
    projectId: 'freemiumhub-9b488',
    authDomain: 'freemiumhub-9b488.firebaseapp.com',
    storageBucket: 'freemiumhub-9b488.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMhEILFHEZxvHu87PHIoIHH-WjvimP5n4',
    appId: '1:246167719483:android:733634c8b68c4ee057161e',
    messagingSenderId: '246167719483',
    projectId: 'freemiumhub-9b488',
    storageBucket: 'freemiumhub-9b488.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBux4SVKkXniK94D6dyEDZBu_fTK5l9yPM',
    appId: '1:246167719483:ios:fce173e0a5d9d7c657161e',
    messagingSenderId: '246167719483',
    projectId: 'freemiumhub-9b488',
    storageBucket: 'freemiumhub-9b488.appspot.com',
    iosClientId: '246167719483-3s3faf2fr6ja3b2m6bof9aolv255aeh1.apps.googleusercontent.com',
    iosBundleId: 'com.example.freemiumHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBux4SVKkXniK94D6dyEDZBu_fTK5l9yPM',
    appId: '1:246167719483:ios:fce173e0a5d9d7c657161e',
    messagingSenderId: '246167719483',
    projectId: 'freemiumhub-9b488',
    storageBucket: 'freemiumhub-9b488.appspot.com',
    iosClientId: '246167719483-3s3faf2fr6ja3b2m6bof9aolv255aeh1.apps.googleusercontent.com',
    iosBundleId: 'com.example.freemiumHub',
  );
}
